services:
  database:
    image: postgres
    container_name: my-broker-db3

    environment:
      - POSTGRES_DB=my_broker_db2
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin@2025 
    
    ports:
      - "5432:5432"